FROM golang:1.23.0-alpine

WORKDIR /debug

COPY go.mod ./
RUN go mod download

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

COPY app ./app
COPY data ./data

EXPOSE 8080


RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o app-debugger ./app
CMD [ "/go/bin/dlv", "--listen=:8080", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/debug/app-debugger" ]